# PortParameters:
carla_port: 2000
main_port: 6000
ego_port: 6001
pygame_port: 6002
traffic_agent_port: 9981
data_port: 9658
tm_port: 8000

# PygameParameters:
screen_width: 1920
screen_height: 1080
screen_main_width: 1080
screen_main_height: 1080
screen_fps: 25.0
map_precision: 15

# WorldParameters:
carla_timeout: 26.0
is_custum_map: False
map_name: Town13
map_path: /home/ujs/mycode/Carla_Truck_Platoon/assets/highways.osm
actor_active_distance: 500
hybrid_physics_radius: 50
tile_stream_distance: 200
synchronous_mode: True
no_rendering_mode: False
fps: 10
fixed_delta_seconds: 0.05


# WeatherParameters:
cloudiness: 0.0
precipitation: 0.0
sun_altitude_angle: 30.0
sun_azimuth_angle: 0

# EmergencyVehicleParameters:
ego_vehicle_type: tesla
local_planner_resolution: 0.5
trajectory_length: 50
global_route_resolution: 5

# TrafficParameters:
bg_vehicle_type:
  - vehicle.audi.a2
  - vehicle.audi.tt
  - vehicle.citroen.c3
  - vehicle.ford.crown
  - vehicle.jeep.wrangler_rubicon
num_vehicles: 3
spwan_points_distance: 50
area_limit:
  min_x: 2000
  max_x: 3000
  min_y: 4200 
  max_y: 5200

# DebugParameters:
camera_height: 60
draw_global_waypoint: False
draw_trajectory: False
draw_spawn_points: False

# DataParameters:
data_folder_path: data